#!/usr/bin/env bash
# Stage 11 — sync Ellen assets from website/assets/ into site/public/images/
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$ROOT/website/assets"
PUBLIC="$ROOT/site/public/images"
PORTRAIT_SRC="$ASSETS/ellen-portrait.jpg"
QR_SRC="$ASSETS/wechat-qr-ellen_inGZ.png"
OG_SRC="$ASSETS/og-share.jpg"
CV_PDF="$ROOT/reference/Ellen_Wang_CV.pdf"

mkdir -p "$PUBLIC/hero" "$PUBLIC/og" "$PUBLIC/contact"

# Bootstrap portrait from CV if not yet in assets/
if [[ ! -f "$PORTRAIT_SRC" ]] && [[ -f "$CV_PDF" ]]; then
  echo "==> Extracting portrait from CV ..."
  tmp="$(mktemp)"
  pdfimages -singlefile -f 1 -l 1 -j "$CV_PDF" "$tmp"
  mv "${tmp}.jpg" "$PORTRAIT_SRC"
fi

if [[ -f "$PORTRAIT_SRC" ]]; then
  echo "==> Processing Ellen portrait ..."
  magick "$PORTRAIT_SRC" \
    -resize 960x960 \
    -quality 88 \
    "$PUBLIC/hero/ellen-portrait.jpg"
  cwebp -q 85 "$PUBLIC/hero/ellen-portrait.jpg" -o "$PUBLIC/hero/ellen-portrait.webp"

  if [[ -f "$OG_SRC" ]]; then
    echo "==> Using custom OG share image ..."
    magick "$OG_SRC" -resize 1200x630^ -gravity center -extent 1200x630 "$PUBLIC/og/og-share.jpg"
  else
    echo "==> Generating OG share card from portrait ..."
    magick -size 1200x630 "gradient:#0072CE-#005BA3" \
      \( "$PUBLIC/hero/ellen-portrait.jpg" -resize 420x420^ -gravity center -extent 420x420 \) \
      -geometry +740+105 -composite \
      -fill white -font Helvetica-Bold -pointsize 52 \
      -annotate +60+220 "Ellen Wang" \
      -fill "#B8D9F0" -font Helvetica -pointsize 28 \
      -annotate +60+290 "IELTS Speaking · Academic English" \
      -fill "#D8E8F5" -font Helvetica -pointsize 22 \
      -annotate +60+340 "Guangzhou · CELTA · DELTA · CertIBET" \
      "$PUBLIC/og/og-share.jpg"
  fi
else
  echo "WARN: No ellen-portrait.jpg — hero keeps stock desk image" >&2
fi

if [[ -f "$QR_SRC" ]]; then
  echo "==> Syncing WeChat QR ..."
  magick "$QR_SRC" -resize 512x512 "$PUBLIC/contact/wechat-qr.png"
else
  echo "NOTE: Add $ASSETS/wechat-qr-ellen_inGZ.png when Ellen provides work QR" >&2
  rm -f "$PUBLIC/contact/wechat-qr.png"
fi

echo "==> Asset sync complete"

MANIFEST="$ROOT/site/src/generated/asset-manifest.ts"
mkdir -p "$(dirname "$MANIFEST")"
portrait="false"
wechat_qr="false"
[[ -f "$PUBLIC/hero/ellen-portrait.webp" || -f "$PUBLIC/hero/ellen-portrait.jpg" ]] && portrait="true"
[[ -f "$PUBLIC/contact/wechat-qr.png" ]] && wechat_qr="true"

cat > "$MANIFEST" <<EOF
/** Auto-generated by scripts/sync-ellen-assets.sh — do not edit. */
export const ASSET_MANIFEST = {
  portrait: $portrait,
  wechatQr: $wechat_qr,
} as const;
EOF

